# Example configuration file for the Trading Agent Bot

# General Settings
general:
  log_level: INFO # The logging level (e.g., DEBUG, INFO, WARNING, ERROR)
  network_url: https://testnet.fuel.network/v1/graphql # The URL of the Fuel network

# o2 Trading Agent Bot Settings
o2:
  base_url: https://api.testnet.o2.app # The base URL for the O2 API

  # o2 Market configuration.
  # Adjust these settings to specify which market to trade on. As of now, only one market configuration is supported.
  market:
    market_id: '0x09c17f779eb0a7658424e48935b2bef24013766f8b3da757becb2264406f9e96' # Market ID
    contract_id: '0x2a78ab167c28f474d2ad62daabe7a42ce03f066dd8aa7cf57b984d14e4bd907b' # Contract ID of the market
    base_symbol: ETH # Base symbol for the market.
    quote_symbol: USDC # Quote symbol for the market.
    reciprocal_rate: false # If true, use the inverse price (1/price) instead of the regular price. Useful for inverse pairs e.g. USDC/USDT -> USDT/USDC.
    order_usdc_value: 10 # Value of each buy/sell order in terms of USDC.
    order_interval_seconds: 1 # Interval between a single buy and sell order, in seconds.
    order_pairs_interval_seconds: 2.5 # Interval between multiple buy & sell order pairs, in seconds.
    bitget_symbol: ETH/USDC # Corresponding Bitget trading symbol. This is used to determine the price of orders on O2. NOTE: Format should always be `BASE/QUOTE`.
    convert_to_usdc: false # Whether to convert the Bitget price quotation to USDC. This is useful for O2 assets that do not have a USDC pair on Bitget. Ex. To get the price of FUEL/USDC we need to fetch the price of FUEL/USDT and USDT/USDC from Bitget as FUEL/USDC is not supported.
    price_adjustment_factor: 0.1 # A factor to adjust the price fetched from Bitget. For example, a value of 0.05 increases the order buy price by 5% and decreases the order sell price by 5%.
    order_type: Spot # Order type for trading. Available options: Spot, FillOrKill.
  account:
    private_key: '<YOUR_PRIVATE_KEY_HERE>' # Private key of a wallet with funds on O2.
    account_type: 'fuel' # Supported: evm or fuel
